require:
  - rubocop/cop/internal_affairs
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
